#pragma once

enum PGL_SPATIAL_STRUCTURE_TYPE
{
    PGL_SPATIAL_STRUCTURE_KDTREE = 0
};

enum PGL_DIRECTIONAL_DISTRIBUTION_TYPE
{
    PGL_DIRECTIONAL_DISTRIBUTION_PARALLAX_AWARE_VMM = 0,
    PGL_DIRECTIONAL_DISTRIBUTION_QUADTREE,
    PGL_DIRECTIONAL_DISTRIBUTION_VMM
};

enum PGL_SPATIAL_SPLIT_TYPE  // for PGL_SPATIAL_STRUCTURE_GENERIC_STREE
{
    PGL_SPATIAL_SPLIT_BASELINE = 0,
    PGL_SPATIAL_SPLIT_ROUNDROBIN,
    PGL_SPATIAL_SPLIT_PPG,
    PGL_SPATIAL_SPLIT_VS,    // variance-scanning
    PGL_SPATIAL_SPLIT_COVS,  // covariance-scanning
    PGL_SPATIAL_SPLIT_IGS,   // information-gain-scanning
    PGL_SPATIAL_SPLIT_FS,    // fluence-scanning
};
