#pragma once

enum PGL_SPATIAL_STRUCTURE_TYPE
{
    PGL_SPATIAL_STRUCTURE_KDTREE = 0
};

enum PGL_DIRECTIONAL_DISTRIBUTION_TYPE
{
    PGL_DIRECTIONAL_DISTRIBUTION_PARALLAX_AWARE_VMM = 0,
    PGL_DIRECTIONAL_DISTRIBUTION_QUADTREE,
    PGL_DIRECTIONAL_DISTRIBUTION_VMM
};

enum PGL_SPATIAL_KNN_TYPE
{
    PGL_SPATIAL_KNN_UNIFORM = 0,  // Baseline
    PGL_SPATIAL_KNN_JITTER,
    PGL_SPATIAL_KNN_IS,   // ISKNN (when precomputation is enabled)
    PGL_SPATIAL_KNN_IS2,  // ISKNN with self's distance set to zero
};

enum PGL_SPATIAL_ANGULAR_THS
{
    PGL_SPATIAL_ANGULAR_HALF_DEG = 0,
    PGL_SPATIAL_ANGULAR_1_DEG,
    PGL_SPATIAL_ANGULAR_3_DEG,
    PGL_SPATIAL_ANGULAR_10_DEG,
};

enum PGL_SPATIAL_SPLIT_KIND
{
    PGL_SPATIAL_SPLIT_NONE = 0,
    PGL_SPATIAL_SPLIT_SAMPLE_COUNT = 0b001,
    PGL_SPATIAL_SPLIT_FLUENCE = 0b010,
    PGL_SPATIAL_SPLIT_ANGULAR = 0b100,
};
