#pragma once

enum PGL_SPATIAL_STRUCTURE_TYPE
{
    PGL_SPATIAL_STRUCTURE_KDTREE = 0
};

enum PGL_DIRECTIONAL_DISTRIBUTION_TYPE
{
    PGL_DIRECTIONAL_DISTRIBUTION_PARALLAX_AWARE_VMM = 0,
    PGL_DIRECTIONAL_DISTRIBUTION_QUADTREE,
    PGL_DIRECTIONAL_DISTRIBUTION_VMM
};

enum PGL_SPATIAL_ANGULAR_TYPE
{
    PGL_SPATIAL_ANGULAR_OFF = 0,
    PGL_SPATIAL_ANGULAR_HEURISTIC,
    PGL_SPATIAL_ANGULAR_SERIES,
    PGL_SPATIAL_ANGULAR_LUT,
};

enum PGL_SPATIAL_KNN_TYPE
{
    PGL_SPATIAL_KNN_UNIFORM = 0,  // Baseline
    PGL_SPATIAL_KNN_REGION_SIZE_WEIGHTED,  // Proposal 1
    PGL_SPATIAL_KNN_JITTER,  // Proposal 2
};

enum PGL_SPATIAL_SPLIT_KIND
{
    PGL_SPATIAL_SPLIT_NONE = 0,
    PGL_SPATIAL_SPLIT_SAMPLE_COUNT = 0b001,
    PGL_SPATIAL_SPLIT_FLUENCE = 0b010,
    PGL_SPATIAL_SPLIT_ANGULAR = 0b100,
};
